first check commit
Antosh2020/2021-2-QA-AUTO-PYTHON-VKGROUP-A-Levishko pull request #2
Opened 2021-11-07 20:54 UTC by Antosh2020

# Домашнее задание № 3

Прошу @sniiick, @crisscuola, @adamakalshchikov, @stpn111, @l0rdyx, @MatveevKirill или @Peace411 проверить его.
Что было сделано:

* Тест на создание сегмента

* Тест на удаление сегмента

* Тест на создание компании

2021-11-08 13:33 UTC, MatveevKirill commented
Не заполнены Reviewers и Assignees.

2021-11-20 09:23 UTC, crisscuola commented on .idea/2021-2-QA-AUTO-PYTHON-VKGROUP-A-Levishko.iml
> +      <sourceFolder url="file://$MODULE_DIR$/api_hw_3" isTestSource="false" />
Полагаю это лишнее в мр

2021-11-20 09:24 UTC, crisscuola commented on api_hw_3/api/client.py
> +		location = "/api/v2/remarketing/segments.json?fields=id,name"
Как вариант можно создать отдельный файлик на все локейшены с говорящими именами и не придётся заводить лишнюю переменную

2021-11-20 09:28 UTC, crisscuola commented on api_hw_3/test_api/base.py
> +    USER = "zdobsizdub@inbox.ru"
Можно вынести в отдельный файлик с кредами

2021-11-20 09:31 UTC, crisscuola commented on selenium_pageobject_hw_2/base.py
> +
Это явно лишнее со второй домашки

2021-11-20 09:31 UTC, crisscuola commented on selenium_pageobject_hw_2/conftest.py
> +
Это явно лишнее со второй домашки

2021-11-20 09:31 UTC, crisscuola commented on selenium_pageobject_hw_2/test_one.py
> +		time.sleep(1)
Это явно лишнее со второй домашки

2021-11-20 09:32 UTC, crisscuola commented on selenium_pageobject_hw_2/ui/fixtures.py
> +
Это явно лишнее со второй домашки

2021-11-20 09:32 UTC, crisscuola commented on selenium_pageobject_hw_2/ui/locators/basic_locators.py
> +	LOGOFF_BUTTON = (By.XPATH, "//a[text()='Log off']")
Это явно лишнее со второй домашки

2021-11-20 09:32 UTC, crisscuola commented on selenium_pageobject_hw_2/ui/locators/profile_locators.py
> +class ProfilePageLocators:
Это явно лишнее со второй домашки

2021-11-20 09:32 UTC, crisscuola commented on selenium_pageobject_hw_2/ui/pages/base_page.py
> +
Это явно лишнее со второй домашки

2021-11-20 09:32 UTC, crisscuola commented on selenium_pageobject_hw_2/ui/pages/main_page.py
> +						self.locators.NAVBAR_LINK_TEMPLATE[1].format(page))
Это явно лишнее со второй домашки

2021-11-20 09:32 UTC, crisscuola commented on selenium_pageobject_hw_2/ui/pages/profile_page.py
> +class ProfilePage(BasePage):
Это явно лишнее со второй домашки

2021-11-20 09:33 UTC, crisscuola requested changes
Давай почистим мр убрав всё лишнее

2021-11-25 09:10 UTC, crisscuola commented
Привет.

Хотелось бы увидеть фикс до 28.11.2021 включительно, иначе работу закрываем как есть.

2021-11-28 21:08 UTC, crisscuola commented
Сроки вышли, закрываю как есть

2021-11-28 21:08 UTC, merged