finish commit
Antosh2020/2021-2-QA-AUTO-PYTHON-VKGROUP-A-Levishko pull request #3
Opened 2021-11-22 20:57 UTC by Antosh2020

# Домашнее задание № 6

Прошу @sniiick, @crisscuola, @adamakalshchikov, @stpn111, @l0rdyx, @MatveevKirill или @Peace411 проверить его.
Что было сделано:

Написаны в формате тестов код для создания БД и добавления access логов из домашнего задания №5.

2021-12-04 20:05 UTC, crisscuola commented on sql_hw_6/mysql/builder.py
> +        return task01
Нейминг так себе, давай что-нибудь более читаемое и осознанное

2021-12-04 20:06 UTC, crisscuola commented on sql_hw_6/tests/base_mysql.py
> +        self.parsed_log = parse_log(self.get_file_path('access.log'))
По сути файл с логами захардкожен, можно через конфтест и парс опшнс сделать параметризированным

2021-12-04 20:07 UTC, crisscuola commented on sql_hw_6/tests/test_mysql.py
> +        assert len(rows) == 5
Ассерты не самые лучше по сути это сравнение что лежит в базе и хардкод чиселкой.
Правильней сравнивать что лежит в базе и что мы попарсим в файле с логами

2021-12-04 20:08 UTC, crisscuola requested changes
Покомментил, основные замечания:
нейминг, ассерты и параметризированный лог файл

2021-12-07 19:58 UTC, stpn111 commented
Привет.
На всякий случай отмечу, что правки необходимо внести до 23:59 субботы.

2021-12-12 22:49 UTC, crisscuola approved these changes
Сроки вышли, баллы выставляем как есть

2021-12-13 22:02 UTC, merged